spring:
  main:
    web-application-type: none

tacocloud:
  api:
    url: http://localhost:8080/orders/fromEmail
  email:
    host: imap.163.com #发送邮件服务器
    mailbox: INBOX
    poll-rate: 10000
    username: gaochanglong1991@163.com # 邮箱
    password: JGMOHWAWQLVCTHAB #客户端授权码
#    protocol: imap #发送邮件协议
#    properties.mail.imap.auth: true
#    properties.mail.imap.port: 994 #465或者994
#    properties.mail.display.sendmail: Javen #可以任意
#    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
#    properties.mail.imap.starttls.enable: true
#    properties.mail.imap.starttls.required: true
#    properties.mail.imap.ssl.enable: true
#    default-encoding: utf-8
#    from: gaochanglong1991@163.com #与上面的username保持一致
# You'll need to tweak these settings to fit an incoming mail server of your choosing.
# JGMOHWAWQLVCTHAB