spring:
  profiles:
    active:
      - feign

server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


---
spring:
  profiles: feign
  application:
    name: ingredient-client


---
spring:
  profiles: webclient
  application:
    name: ingredient-client

